### ISSUE TITLE
Create noops for docker client if not available

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/chrisomatic#5]
We want `chrisomatic` to work without access to docker (albeit with a limited feature set, such as being unable to create admin users or run plugins to get their info).

**Comment by lumuchris256** [comment]
@jennydaman with a little prep up . i can be useful around here

**Comment by jennydaman** [comment]
Message me on Matrix, we can set up a time!

**Comment by jennydaman** [comment]
Fixed in https://github.com/FNNDSC/chrisomatic/commit/81ba0d6bc926d1611c9858ec52b2b79e1a1822ec
